name: CI/CD - Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cloud-cicd-app .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cloud-infrastructure-cicd
            git pull origin main
            sudo docker stop cloud-cicd-container || true
            sudo docker rm cloud-cicd-container || true
            sudo docker build -t cloud-cicd-app .
            sudo docker run -d -p 5000:5000 --name cloud-cicd-container cloud-cicd-app
